### ISSUE TITLE
咨询下sendCode.js是只能发送给自己的机器人么？

### ISSUE THREAD

**Issue by xxp2277** [q4w5e6/selfUse#2]
首先谢谢作者的辛勤劳动，咨询下sendCode.js能不能将互助码直接发送给@TuringLabbot(id:1346086685)。目前我只能发送给自己的机器人(TG_PUSH_ID 填写的值与TG_USER_ID一致能成功发送给自己id100开头的机器人)。
想问的是目前仅能转发还是能直接发送？

**Comment by q4w5e6** [comment]
> 首先谢谢作者的辛勤劳动，咨询下sendCode.js能不能将互助码直接发送给@TuringLabbot(id:1346086685)。目前我只能发送给自己的机器人(TG_PUSH_ID 填写的值与TG_USER_ID一致能成功发送给自己id100开头的机器人)。
> 想问的是目前仅能转发还是能直接发送？

仅组合互助码转发，不做自动上车。

**Comment by xxp2277** [comment]
大佬，有个类似问题，不另外发issue了。比如/submit_activity_codes fruit ，农场应该是farm而非fruit？还是有另外的车，可否告知？

**Comment by xxp2277** [comment]
大佬，有个类似问题，不另外发issue了。比如/submit_activity_codes fruit ，农场应该是farm而非fruit？还是有另外的车，可否告知？

**Comment by thy486** [comment]
> 大佬，有个类似问题，不另外发issue了。比如/submit_activity_codes fruit ，农场应该是farm而非fruit？还是有另外的车，可否告知？

所以是自用，非分享脚本，不做任何维护。

**Comment by xxp2277** [comment]
> 
> 
> > 大佬，有个类似问题，不另外发issue了。比如/submit_activity_codes fruit ，农场应该是farm而非fruit？还是有另外的车，可否告知？
> 
> 所以是自用，非分享脚本，不做任何维护或者兼容。

好的，已经很好了。生成的东西需要修改的内容很少了。多谢了。
